### ISSUE TITLE
Bug: lists of solutions not remembered in Firefox Nightly

### ISSUE THREAD

**Issue by Atervanda** [blmage/duolingo-solution-viewer#100]
I love that you can see the solutions from the sentence discussions, but I didn't notice it until now because this feature is not supported in Firefox Nightly (my standard browser). I can confirm it does work in Firefox.

I understand it's not a priority, but if you could somehow get it to work in Nightly that would be fantastic.

**Comment by blmage** [comment]
I just tested it with Firefox Nightly, and it seems to work fine. 

In case this might be related, solutions to listening challenges are (currently) not available from the sentence discussions. If you can confirm that this doesn't work for any challenge on your end, I'll prepare a set of instructions to help with debugging this problem.

**Comment by Atervanda** [comment]
Thanks for your reply. I just tried it again in version 81.0a1 (2020-08-18) (64-bit), on two different accounts, and it doesn't work for any challenge.

**Comment by blmage** [comment]
Sorry for the delay, I did not forget about this! (I'll find some time next week to prepare a debugging walkthrough video)

**Comment by blmage** [comment]
@Atervanda  Sorry again! The video is available here: https://streamable.com/xherey, can you check it and report the steps you couldn't reproduce?

**Comment by Atervanda** [comment]
@blmage Thanks so much! This is what I get: https://streamable.com/6imr3q

As you can see at around 0:50, I don't get the same response you get, and I guess the request cookies show I'm supposedly not signed in?

(Tested with all other add-ons disabled, on both duolingo.com and preview.duolingo.com, on three accounts.)

**Comment by blmage** [comment]
Thank you very much for the video!

Yes, this seems to almost certainly be related to the absence of certain cookies in the requests - I'll investigate whether we can move these requests from the background script to the content script (we don't have control over the request cookies), and keep you updated.

**Comment by blmage** [comment]
Should be fixed in version `3.0.5`, but don't hesitate to reopen this issue if that's not the case on Firefox Nightly.

**Comment by Atervanda** [comment]
Thanks so much, @blmage, but I'm afraid it still doesn't work for me in Nightly. (Exact same behavior.) Don't feel pressured to investigate further just for my sake, though. Nightly had been causing some other problems for me recently, so I switched my main browser to Firefox Developer edition, where your extension works perfectly.
